/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RateLimitImport } from './routes/rateLimit'
import { Route as IndexImport } from './routes/index'
import { Route as TestauthIndexImport } from './routes/testauth/index'
import { Route as SummonerRegionRiotIdImport } from './routes/summoner/$region.$riotId'

// Create/Update Routes

const RateLimitRoute = RateLimitImport.update({
  id: '/rateLimit',
  path: '/rateLimit',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestauthIndexRoute = TestauthIndexImport.update({
  id: '/testauth/',
  path: '/testauth/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerRegionRiotIdRoute = SummonerRegionRiotIdImport.update({
  id: '/summoner/$region/$riotId',
  path: '/summoner/$region/$riotId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/rateLimit': {
      id: '/rateLimit'
      path: '/rateLimit'
      fullPath: '/rateLimit'
      preLoaderRoute: typeof RateLimitImport
      parentRoute: typeof rootRoute
    }
    '/testauth/': {
      id: '/testauth/'
      path: '/testauth'
      fullPath: '/testauth'
      preLoaderRoute: typeof TestauthIndexImport
      parentRoute: typeof rootRoute
    }
    '/summoner/$region/$riotId': {
      id: '/summoner/$region/$riotId'
      path: '/summoner/$region/$riotId'
      fullPath: '/summoner/$region/$riotId'
      preLoaderRoute: typeof SummonerRegionRiotIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rateLimit': typeof RateLimitRoute
  '/testauth': typeof TestauthIndexRoute
  '/summoner/$region/$riotId': typeof SummonerRegionRiotIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rateLimit': typeof RateLimitRoute
  '/testauth': typeof TestauthIndexRoute
  '/summoner/$region/$riotId': typeof SummonerRegionRiotIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/rateLimit': typeof RateLimitRoute
  '/testauth/': typeof TestauthIndexRoute
  '/summoner/$region/$riotId': typeof SummonerRegionRiotIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rateLimit' | '/testauth' | '/summoner/$region/$riotId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rateLimit' | '/testauth' | '/summoner/$region/$riotId'
  id:
    | '__root__'
    | '/'
    | '/rateLimit'
    | '/testauth/'
    | '/summoner/$region/$riotId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RateLimitRoute: typeof RateLimitRoute
  TestauthIndexRoute: typeof TestauthIndexRoute
  SummonerRegionRiotIdRoute: typeof SummonerRegionRiotIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RateLimitRoute: RateLimitRoute,
  TestauthIndexRoute: TestauthIndexRoute,
  SummonerRegionRiotIdRoute: SummonerRegionRiotIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rateLimit",
        "/testauth/",
        "/summoner/$region/$riotId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/rateLimit": {
      "filePath": "rateLimit.ts"
    },
    "/testauth/": {
      "filePath": "testauth/index.tsx"
    },
    "/summoner/$region/$riotId": {
      "filePath": "summoner/$region.$riotId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
