/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SummonerRegionRiotIdImport } from './routes/summoner/$region.$riotId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerRegionRiotIdRoute = SummonerRegionRiotIdImport.update({
  id: '/summoner/$region/$riotId',
  path: '/summoner/$region/$riotId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/summoner/$region/$riotId': {
      id: '/summoner/$region/$riotId'
      path: '/summoner/$region/$riotId'
      fullPath: '/summoner/$region/$riotId'
      preLoaderRoute: typeof SummonerRegionRiotIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/summoner/$region/$riotId': typeof SummonerRegionRiotIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/summoner/$region/$riotId': typeof SummonerRegionRiotIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/summoner/$region/$riotId': typeof SummonerRegionRiotIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/summoner/$region/$riotId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/summoner/$region/$riotId'
  id: '__root__' | '/' | '/summoner/$region/$riotId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SummonerRegionRiotIdRoute: typeof SummonerRegionRiotIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SummonerRegionRiotIdRoute: SummonerRegionRiotIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/summoner/$region/$riotId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/summoner/$region/$riotId": {
      "filePath": "summoner/$region.$riotId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
