name: Fetch and Update Datasets

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Datasets
        run: |
          mkdir -p src/_datasets  # Create the datasets directory if it doesn't exist
          set -e  # Exit immediately if a command exits with a non-zero status

          echo "Fetching versions..."
          curl -fs "https://ddragon.leagueoflegends.com/api/versions.json" | jq '.' > src/_datasets/versions.json
          patchVer=$(jq -r '.[0]' src/_datasets/versions.json)  # Extract the latest version
          echo "patchVer=$patchVer" >> $GITHUB_ENV # Export patchVer for subsequent steps

          if [ -z "$patchVer" ]; then
            echo "Failed to fetch DataDragon version."
            exit 1
          fi

          echo "Fetching champion dataset..."
          curl -fs "https://ddragon.leagueoflegends.com/cdn/${patchVer}/data/en_US/champion.json" | jq '.' > src/_datasets/champion.json
          echo "Fetching runes dataset..."
          curl -fs "https://ddragon.leagueoflegends.com/cdn/${patchVer}/data/en_US/runesReforged.json" | jq '.' > src/_datasets/runesReforged.json
          echo "Fetching summoner spells dataset..."
          curl -fs "https://ddragon.leagueoflegends.com/cdn/${patchVer}/data/en_US/summoner.json" | jq '.' > src/_datasets/summoner.json
          echo "Fetching items dataset..."
          curl -fs "https://ddragon.leagueoflegends.com/cdn/${patchVer}/data/en_US/item.json" | jq '.' > src/_datasets/item.json
          echo "Fetching queues dataset..."
          curl -fs "https://static.developer.riotgames.com/docs/lol/queues.json" | jq '.' > src/_datasets/queues.json
          echo "Fetching maps dataset..."
          curl -fs "https://static.developer.riotgames.com/docs/lol/maps.json" | jq '.' > src/_datasets/maps.json
          echo "Fetching arena dataset..."
          curl -fs "https://raw.communitydragon.org/latest/cdragon/arena/en_us.json" | jq '.' > src/_datasets/arena.json

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add src/_datasets/*.json  # Add all JSON files
          git commit -m "GHA: Update datasets (v${{ env.patchVer }})" || echo "No changes to commit"
          git push
